version: ~> 1.0
language: c
branches:
  only:
    - master
dist: bionic
addons:
  snaps:
    - name: cmake
      confinement: classic
      channel: latest/stable
  apt:
    update: true
    packages:
      - ninja-build
  homebrew:
    update: true
    packages:
      - cmake
      - ninja
jobs:
  include:
    - os: linux
      arch: amd64
      compiler: gcc
    - os: linux
      arch: amd64
      compiler: clang
    - os: linux
      arch: arm64
      compiler: gcc
    - os: linux
      arch: s390x
      compiler: gcc
    - os: linux
      arch: arm64-graviton2
      virt: lxd
      group: edge
      compiler: gcc
    - os: linux
      arch: arm64
      compiler: clang
    - os: osx
      osx_image: xcode14.2
      compiler: clang
    - os: linux-ppc64le
      compiler: gcc
before_script:
  - ./configure.sh cmake-info
script:
  - ./configure.sh build
